In [4]:
import numpy as np 


In [6]:
array_temp = np.random.randint(0, 100, size=(10, 3))
print(array_temp)

[[45 13 93]
 [25 66 14]
 [19  3 35]
 [66 26 50]
 [51 71 71]
 [30 47 12]
 [56 26  1]
 [85 60 91]
 [94 88 54]
 [84 30 44]]
